<a href="https://colab.research.google.com/github/ponskillhub/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.1.0+cu121


## Introduction to Tensors

### scalars

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

### vectors

In [4]:
vector = torch.tensor([7,9])
vector

tensor([7, 9])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

### matrix

In [8]:
MATRIX = torch.tensor([[7,8],
                       [9,10]

])

In [9]:
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
TENSOR = torch.tensor(
    [[[1,2,3],
      [4,5,6],
      [7,8,9]]]

)
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

# Random values tensors

In [16]:
random_tensor = torch.rand(1,10,10)
random_tensor

tensor([[[0.8589, 0.4339, 0.6220, 0.6108, 0.2584, 0.4613, 0.4040, 0.1373,
          0.1809, 0.8468],
         [0.4253, 0.4388, 0.6367, 0.3649, 0.0581, 0.8903, 0.1823, 0.6208,
          0.8653, 0.2032],
         [0.5345, 0.0141, 0.7804, 0.2128, 0.5687, 0.9566, 0.4467, 0.8119,
          0.4827, 0.2888],
         [0.9497, 0.4420, 0.1823, 0.1152, 0.5024, 0.1174, 0.0252, 0.6088,
          0.8970, 0.7972],
         [0.7450, 0.6049, 0.0229, 0.1736, 0.5063, 0.0411, 0.5736, 0.8871,
          0.0856, 0.6913],
         [0.2001, 0.1243, 0.4677, 0.1102, 0.1883, 0.3615, 0.0807, 0.3402,
          0.3978, 0.4292],
         [0.3578, 0.4412, 0.3182, 0.9794, 0.0419, 0.9996, 0.1898, 0.8454,
          0.6221, 0.6609],
         [0.7066, 0.4243, 0.0044, 0.9844, 0.0639, 0.5897, 0.3893, 0.0560,
          0.4599, 0.4622],
         [0.1486, 0.3337, 0.5038, 0.8042, 0.3999, 0.1361, 0.0804, 0.9737,
          0.1313, 0.7181],
         [0.5124, 0.9770, 0.0620, 0.6865, 0.6391, 0.9716, 0.2119, 0.3501,
          0.3617,

# create a rendam tensor with similar shape to an image

In [20]:
random_image_tensor = torch.rand(3,224,224)
random_image_tensor

tensor([[[0.4651, 0.5584, 0.5216,  ..., 0.7827, 0.2382, 0.7634],
         [0.7472, 0.7320, 0.9543,  ..., 0.8469, 0.4156, 0.9371],
         [0.7936, 0.9566, 0.0272,  ..., 0.2574, 0.4470, 0.8538],
         ...,
         [0.4438, 0.3150, 0.4217,  ..., 0.5240, 0.2449, 0.6786],
         [0.9546, 0.3935, 0.5558,  ..., 0.7401, 0.3450, 0.8779],
         [0.5016, 0.4457, 0.3795,  ..., 0.8316, 0.7825, 0.2937]],

        [[0.5355, 0.6693, 0.7708,  ..., 0.7737, 0.4989, 0.1885],
         [0.7433, 0.1527, 0.5114,  ..., 0.6748, 0.5172, 0.4426],
         [0.1612, 0.1610, 0.8920,  ..., 0.3188, 0.8312, 0.3389],
         ...,
         [0.9155, 0.8181, 0.2369,  ..., 0.5416, 0.6656, 0.3033],
         [0.2439, 0.1744, 0.3661,  ..., 0.4348, 0.1374, 0.8447],
         [0.8222, 0.9648, 0.9914,  ..., 0.2403, 0.7739, 0.0017]],

        [[0.2172, 0.0142, 0.8343,  ..., 0.4499, 0.0064, 0.2020],
         [0.4686, 0.6516, 0.4182,  ..., 0.1629, 0.3792, 0.9776],
         [0.6802, 0.1747, 0.7307,  ..., 0.2832, 0.6395, 0.

# tensors of zeros

In [21]:
zero_tensor = torch.zeros(size=(2,3))
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

## tensors of ones

In [22]:
ones_tensor = torch.ones(size=(2,3))
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [23]:
ones_tensor.dtype

torch.float32

# range

In [24]:
range = torch.arange(0,10)
range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
range = torch.arange(start=1,end=11,step=1)
range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## tensors like

In [28]:
ten_like = torch.zeros_like(input=ones_tensor)
ten_like

tensor([[0., 0., 0.],
        [0., 0., 0.]])

## tensor datatype

In [29]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False
                               )
float_32_tensor.dtype

torch.float32

In [30]:
float_32_tensor.device

device(type='cpu')

In [31]:
float_32_tensor.requires_grad

False

## change the data type of tensor

In [32]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

## Tensor Operations

In [34]:
tensor = torch.tensor([10,11,12])
tensor += 1
tensor

tensor([11, 12, 13])

In [35]:
tensor * 10

tensor([110, 120, 130])

In [36]:
tensor - 1

tensor([10, 11, 12])

In [37]:
torch.mul(tensor,10)

tensor([110, 120, 130])

In [38]:
torch.add(tensor, 5)

tensor([16, 17, 18])